// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCountries.Model;

namespace WebApiCountries.Migrations
{
    [DbContext(typeof(CountriesDbContext))]
    partial class CountriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiCountries.Model.Countries", b =>
                {
                    b.Property<short>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlphaOneCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlphaTwoCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Independent")
                        .HasColumnType("bit");

                    b.Property<string>("NameCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("WebApiCountries.Model.SubDivision", b =>
                {
                    b.Property<short>("SubDivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeSubDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("NameSubDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("countriesCountryId")
                        .HasColumnType("smallint");

                    b.HasKey("SubDivisionId");

                    b.HasIndex("countriesCountryId");

                    b.ToTable("subDivision");
                });

            modelBuilder.Entity("WebApiCountries.Model.SubDivision", b =>
                {
                    b.HasOne("WebApiCountries.Model.Countries", "countries")
                        .WithMany("subDivision")
                        .HasForeignKey("countriesCountryId");

                    b.Navigation("countries");
                });

            modelBuilder.Entity("WebApiCountries.Model.Countries", b =>
                {
                    b.Navigation("subDivision");
                });
#pragma warning restore 612, 618
        }
    }
}
